[package]
name = "opengl"
version = "0.1.0"
authors = ["OrangeBacon <computer.backup.15@gmail.com>"]
edition = "2018"

[dependencies]
sdl2 = { version = "0.34.3", features = ["bundled", "static-link"] }
gl = { path = "lib/gl" }
image = "0.23.12"
nalgebra = "0.24"

[build-dependencies]
walkdir = "2"

[features]
gl_debug = ["gl/debug"]
